---
title: "R Notebook"
output: html_notebook
---

Playing with git log analysis

```{r}
# Parts 1 and 2
library(tidyverse)
library(glue)
library(stringr)
library(forcats)

```


```{r}
# Remote repository URL
repo_url <- "https://github.com/tidyverse/ggplot2.git"
# Directory into which git repo will be cloned
clone_dir <- file.path(tempdir(), "git_repo")
# Create command
clone_cmd <- glue("git clone {repo_url} {clone_dir}")
# Invoke command
system(clone_cmd)
```

```{r}

system(glue('git -C {clone_dir} log -3'))

```


```{r}
log_format_options <- c(datetime = "cd", commit = "h", parents = "p", author = "an", subject = "s")
option_delim <- "\t"
log_format   <- glue("%{log_format_options}") %>% glue_collapse(option_delim)
log_options  <- glue('--pretty=format:"{log_format}" --date=format:"%Y-%m-%d %H:%M:%S"')
log_cmd      <- glue('git -C {clone_dir} log {log_options}')
log_cmd

```



```{r}
system(glue('{log_cmd} -3'))
```


```{r}
history_logs <- system(log_cmd, intern = TRUE) %>% 
  str_split_fixed(option_delim, length(log_format_options)) %>% 
  as_tibble() %>% 
  setNames(names(log_format_options))

```

```{r}
history_logs
```

```{r}
# Because the parents commit can be multiple parents, we change that column into a list.

history_logs <- history_logs %>% 
  mutate(parents = str_split(parents, " "))

```

```{r}
history_logs

```

```{r}
# I don't know what's going on here, or why there's a loop instead of a function with lapply or map

# Finally, be sure to assign branch numbers to commits. There’s surely a better way to do this, but here’s one (very untidy) method:

# Start with NA
history_logs <- history_logs %>% mutate(branch = NA_integer_)


```

```{r}
history_logs
```


```{r}
# Create a boolean vector to represent free columns (1000 should be plenty!)
free_col <- rep(TRUE, 1000)

```


```{r}

for (i in seq_len(nrow(history_logs) - 1)) { # - 1 to ignore root # The seq_len creates a sequence from 1 to the number of rows in history (minus one, to ignore the initial commit which doesn't have a parent). So we are going to loop through the entire dataframe.
  # Check current branch col and assign open col if NA (NA means we haven't evaluated it yet)
  branch <- history_logs$branch[i] # Building a vector called branch, with value NA_integer
  if (is.na(branch))  #It's NA (the first time), so we perform this loop
    branch <- which.max(free_col) #the which.max the first time should be 1, so branch is now 1
    free_col[branch] <- FALSE # And now the first entry in free_col is false, with the other 999 as TRUE
    history_logs$branch[i] <- branch #and now we have branch as 1, so this loop will end because it's no longer NA.
  } 
  # Go through parents
  parents <- history_logs$parents[[i]] # Assign parents the object in the i'th row. We look through the entire dataframe each time.
  for (p in parents) { # Parents is a list. So this loop looks through the list of parents in the row.
    parent_col <- history_logs$branch[history_logs$commit == p] # we create a vector and assign the row where the commit is equal to the parent
    # If col is missing, assign it to same branch (if first parent) or new
    # branch (if other)
    if (is.na(parent_col)) { #If there's no parent, it means there's a new branch?
      parent_col <- if_else(p == parents[1], branch, which.max(free_col)) # If 
    # If NOT missing this means a split has occurred. Assign parent the lowest
    # and re-open both cols (parent closed at the end)
    } else {
      free_col[c(branch, parent_col)] <- TRUE 
      parent_col <- min(branch, parent_col)
    }
    # Close parent col and assign
    free_col[parent_col] <- FALSE
    history_logs$branch[history_logs$commit == p] <- parent_col #We place the value in the history_log and go through the loop
  }
}
```


# Analysis 

```{r}

history_logs %>% 
  count(author, sort = TRUE)

```
# What files did a particular author work on?

```{r}
log_format_options <- c(datetime = "cd", commit = "h", parents = "p", author = "an", subject = "s")
option_delim <- "\t"
log_format   <- glue("%{log_format_options}") %>% glue_collapse(option_delim)
log_options  <- glue('--pretty=format:"{log_format}" --date=format:"%Y-%m-%d %H:%M:%S"')
log_cmd      <- glue('git -C {clone_dir} log {log_options}')
log_cmd

```

```{r}
#All files to which hadley contributed

hadley <- system(glue('git -C {clone_dir} log --no-merges --author="hadley" --name-only --pretty=format:"" | sort -u'), intern = TRUE) %>%
  as_tibble()

```

```{r}
#All files to which everyone contributed

everyone <- system(glue('git -C {clone_dir} log --no-merges --name-only --pretty=format:"" | sort -u'), intern = TRUE) %>%
  as_tibble()

```

```{r}

# Look at the difference to see what hadley did NOT contribute to. Seems like a clunky way to do it, but I don't know an alternative. 

nothadley <- subset(everyone, !(value %in% hadley$value))

```


```{r}

system(git {clone_dir} log --pretty="%H" --author="authorname" | while read commit_hash; do git show --oneline --name-only $commit_hash | tail -n+2; done | sort | uniq)


```

# What files did a particular author NOT work on?



```{r}
# Remove the cloned depot

unlink(clone_dir, recursive = TRUE)

```


```{r}
# Fix names

history_logs <- history_logs %>% 
  mutate(author = case_when(
    str_detect(tolower(author), "hadley") ~ "Hadley Wickham",
    str_detect(tolower(author), "kohske takahashi") ~ "Kohske Takahashi",
    TRUE ~ str_to_title(author)
  ))

```

```{r}

history_logs %>% 
  count(author) %>% 
  top_n(10, n) %>% 
  mutate(author = fct_reorder(author, n)) %>% 
  ggplot(aes(author, n)) +
    geom_col(aes(fill = n), show.legend = FALSE) +
    coord_flip() +
    theme_minimal() +
    ggtitle("ggplot2 authors with most commits") +
    labs(x = NULL, y = "Number of commits", caption = "Post by @drsimonj")

```



```{r}
# Part 3
library(tidygraph)
library(ggraph)
library(tidytext)
```



```{r}
# Convert commit to a factor (for ordering nodes)
history_logs <- history_logs %>% 
  mutate(commit = factor(commit))
# Nodes are the commits (keeping relevant info)
nodes <- history_logs %>% 
  select(-parents) %>% 
  arrange(commit)
# Edges are connections between commits and their parents
edges <- history_logs %>% 
  select(commit, parents) %>% 
  unnest(parents) %>% 
  mutate(parents = factor(parents, levels = levels(commit))) %>% 
  transmute(from = as.integer(parents), to = as.integer(commit)) %>% 
  drop_na()
# Create tidy directed graph object
git_graph <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE)
git_graph
```


```{r}
git_graph %>% 
  ggraph() +
    geom_edge_link(alpha = .1) +
    geom_node_point(aes(color = factor(branch)), alpha = .3) +
    theme_graph() +
    theme(legend.position = "none")
#> Using `nicely` as default layout

```
```{r}
ggraph_git <- . %>%
  # Set node x,y coordinates
  activate(nodes) %>% 
  mutate(x = datetime, y = branch) %>% 
  # Plot with correct layout
  create_layout(layout = "manual", node.positions = as_tibble(activate(., nodes))) %>% 
  {ggraph(., layout = "manual") + theme_graph() + labs(caption = "Post by @drsimonj")}
```

```{r}

ggraph_git

```



```{r}

# This throws an error because ggraph has been updated. See https://github.com/thomasp85/ggraph/issues/130  

# To fix this, we MUST really understand what the original code is trying to do, and then understand how updated ggraph does it...



git_graph %>% 
  ggraph_git() +
    geom_edge_link(alpha = .1) +
    geom_node_point(aes(color = factor(branch)), alpha = .3) +
    theme(legend.position = "none") +
    ggtitle("Commit history of ggplot2")
```


```{r}

data(stop_words)
tidy_subjects <- history_logs %>%
  unnest_tokens(word, subject) %>% 
  anti_join(stop_words)
#> Joining, by = "word"

```

```{r}

tidy_subjects

```

```{r}
tidy_subjects %>%
  count(word) %>% 
  top_n(10, n) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
    geom_col(aes(fill = n), show.legend = FALSE) +
    coord_flip() +
    theme_minimal() +
    ggtitle("Most-used words in ggplot2 commit subjects") +
    labs(x = NULL, y = "Word frequency", caption = "Post by @drsimonj")

```


```{r}
history_logs %>% 
  select(commit, author, subject) %>% 
  unnest_tokens(bigram, subject, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(word1 == "fix") %>%
  anti_join(stop_words, by = c("word2" = "word")) %>% 
  count(word2, sort = TRUE)

```

